language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - "python setup.py install"
    - "pip install pypt[tests] coveralls pylama"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test"
    - "pylama"
after_success:
    - coveralls
