language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - "python setup.py develop"
    - "pip install pyramid_decoy[tests] coveralls pylama"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test -v --cov pyramid_decoy tests/"
    - "pylama"
after_success:
    - coveralls
