dist: xenial
language: python
sudo: false
python:
    - 3.9
    - 3.8
    - 3.7
    - 3.6
# blocklist branches
branches:
  except:
  - requires-io-master
install:
    - pip install -r requirements-test.txt
    - pip install .[tests] coveralls wheel
script:
    - py.test -v --cov pyramid_decoy tests/
after_success:
    - coveralls
jobs:
    include:
      - stage: linters
        install:
          - pip install -r requirements-lint.txt
          - pip install .[tests] coveralls wheel
        script:
          - pycodestyle
          - pydocstyle
          - pylint pyramid_decoy tests
        after_success: skip
      - stage: deploy
        if: tag IS present
        script: skip
        deploy:
            provider: pypi
            user: fizyk
            password:
                secure: IheB1tyDOLJsBh86IPCF95x88u88iz/FRjoC/FdhJEQ+u3MidFDrUKhVeG5sisAnjYKdVfkrrygLfOd8TvGHYgvy+lnKFjpLFt76qLqAgnYoOgQcXs9vFPjRExXeM19G9RwEIfXh435M2WOZEZM8HU3jiva0Xol3ebqVu7o1s18=
            on:
                tags: true
                repo: fizyk/pyramid_decoy
            distributions: sdist bdist_wheel
